### PR TITLE
Use System HarfBuzz

### LINKED ISSUE #45: Option to link against installed harfbuzz
My harfbuzz is often not like your harfbuzz, so downloading and building a vendor harfbuzz isn't something I want uharfbuzz to do. Obviously it's a good idea for platforms where you can't be sure harfbuzz is installed already, but it's unnecessary in many cases when you can just link against the system version. Can we make that an option?

### PR DESCRIPTION
**Pull request by BwL1289**
Resolves #45.

Adds the ability to use system HarfBuzz and associated documentation.

### CODE REVIEW

**Comment by BwL1289** [comment]
@khaledhosny please let me know if this is acceptable.

CC @gorloffslava.

**Comment by anthrotype** [comment]
thanks for this PR!
it's not clear to me why should pypy 3.8 fail on the CI but 3.7 still work.. From the error message it might even be some bug in setuptools and/or pypy itself.
It doesn't seem like you made any changes to our own CI workflow, it's still only building the uharfbuzz module with vendored harfbuzz, which was working before this PR, so it's not clear to me why it would start failing now.
I just pushed an empty commit to this https://github.com/harfbuzz/uharfbuzz/pull/202 (based off main) to see if it triggers there as well, without your changes.
Maybe we could also try to build with a more up to date PyPy version, if that works i'm happy to drop the ones that are currently failing.

**Comment by BwL1289** [comment]
@anthrotype awesome - thanks so much for the help on this. really appreciate it.

**Comment by anthrotype** [comment]
it looks like it failed with the same error so your PR is not the culprit
https://github.com/harfbuzz/uharfbuzz/actions/runs/10512034395/job/29124400429?pr=202#step:5:3264

I'd say let's not block this PR on the PyPy issue.

I was wondering, how easy or difficult would be to set up the CI to also test with USE_SYSTEM_LIBS=1? It'd be ok to only test this on linux

**Comment by BwL1289** [comment]
> it looks like it failed with the same error so your PR is not the culprit https://github.com/harfbuzz/uharfbuzz/actions/runs/10512034395/job/29124400429?pr=202#step:5:3264
> 
> I'd say let's not block this PR on the PyPy issue.

Thank you!

> I was wondering, how easy or difficult would be to set up the CI to also test with USE_SYSTEM_LIBS=1? It'd be ok to only test this on linux

 I can put this in our backlog. We're juggling a lot with a small team (other contributions to tons of open source libs in addition to the platform we're building) so anything we can offload for now is greatly appreciated.

**Comment by anthrotype** [comment]
thanks, I just tested this locally and it can confirm it works. I'll open an issue for exercising the USE_SYSTEM_LIBS=1 on our CI as well.

**Comment by BwL1289** [comment]
Thanks @anthrotype

**Comment by anthrotype** [comment]
https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.39.4

**Pull request merged**
