### PR TITLE
configure pytest to only look in tests/ by default 

### PR DESCRIPTION
**Pull request by anthrotype**
Attempt to fix https://github.com/harfbuzz/uharfbuzz/issues/86

### CODE REVIEW

**Comment by anthrotype** [comment]
yes, this seems to fix it

see that "Removing test/subset/__pycache__/"

https://ci.appveyor.com/project/fonttools/uharfbuzz/builds/39211316#L384

**Comment by justvanrossum** [comment]
LGTM. If the CI completes succesfully, shall I merge and tag release v0.16.1?

**Comment by anthrotype** [comment]
could it be that when we do `pytest`, it attempts to discover tests in all the subfolders including those that don't pertain to uharfbuzz itself? maybe we should exclude the harfbuzz dir or tell pytest to only look for tests inside the tests/ directory

**Comment by justvanrossum** [comment]
Ahh, that could easily be it! I noticed that I had to run "pytest tests" because it was picking up some test-ish trash I havd lying around.

**Comment by anthrotype** [comment]
yep, that's it

**Comment by anthrotype** [comment]
now running `pytest` without arguments will default to `pytest tests/`

**Comment by anthrotype** [comment]
> LGTM. If the CI completes succesfully, shall I merge and tag release v0.16.1?

yes please thanks!

**Pull request merged**
