### PR TITLE
[draw API] Get another 10-15% speedup by pre-fetching the pen instance methods

### PR DESCRIPTION
**Pull request by justvanrossum**
Pre-fetching the pen instance methods and passing them via `user_data` speeds up pen drawing by another 10-15%.

### CODE REVIEW

**Comment by behdad** [comment]
I'm glad you are finding the user_data useful!

**Comment by justvanrossum** [comment]
> I'm glad you are finding the user_data useful!

Totally! It appears to me this is exactly what `user_data` is good at: passing method-specific implementations. `DrawFuncs` objects should do the same for the pure Python callbacks.

**Comment by behdad** [comment]
> Totally! It appears to me this is exactly what `user_data` is good at: passing method-specific implementations

Correct. That's what they are for.

**Comment by behdad** [comment]
Typically the user_data is bound to the method to call for that particular call, whereas the draw_data is bound to the instance.

**Comment by behdad** [comment]
I've got to say what you and Khaled are doing with this API is all magic to me.

**Comment by justvanrossum** [comment]
Right. In this case `user_data` is both, as I'm using it to pass bound methods.

**Comment by khaledhosny** [comment]
> I've got to say what you and Khaled are doing with this API is all magic to me.

A well designed API allows its users to do things not imagined by its designers 😉  (I think there was a saying somehow like that, or may be I’m making things up)

**Pull request merged**
