### PR TITLE
Enable Windows build on GH actions

### LINKED ISSUE #86: No win_amd64 wheels were produced for last release (0.16.0)
https://pypi.org/project/uharfbuzz/0.16.0/#files

### PR DESCRIPTION
**Pull request by justvanrossum**
Trying to see if this "just works". Perhaps it can fix #86.

### CODE REVIEW

**Comment by justvanrossum** [comment]
So that didn't work. I wonder if it's a pytest issue, similar to https://github.com/pytest-dev/pytest/issues/7951

```
  =================================== ERRORS ====================================
  ________________________ ERROR collecting test session ________________________
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\runner.py:311: in from_call
      result: Optional[TResult] = func()
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\runner.py:341: in <lambda>
      call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\main.py:690: in collect
      for direntry in visit(str(argpath), self._recurse):
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:606: in visit
      yield from visit(entry.path, recurse)
  users\runneradmin\appdata\local\temp\tmp1rj1ttgu\lib\site-packages\_pytest\pathlib.py:591: in visit
      for entry in os.scandir(path):
  E   OSError: [WinError 1921] The name of the file cannot be resolved by the system: 'c:\\Documents and Settings\\All Users\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data'
  =========================== short test summary info ===========================
  ERROR  - OSError: [WinError 1921] The name of the file cannot be resolved by ...
  !!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
  ======================== 1 error in 598.94s (0:09:58) =========================
```

**Comment by anthrotype** [comment]
hm, but do we have a recursive symlink?

**Comment by justvanrossum** [comment]
Not that I know. It's crashing in visiting 'c:\\Documents and Settings\\All Users\\Application Data', and I don't know what it's doing there.

**Comment by justvanrossum** [comment]
So now that #88 fixed #86, this PR is no longer needed, but it is still nice to have, so leaving this open, in case anyone knows how to fix it.

**Comment by khaledhosny** [comment]
This is now working. It was failing because we have `CIBW_TEST_COMMAND: "cd {project} && pytest"`, and on GitHub Actions `{project}` points to a directory on the D: drive, but `cd` on Windows does not change drive by default and silently fails, so we we running `pytest` on the root of C: drive. Using `pushd` seems to work on the three platforms.

Should we drop AppVeyor use and merge this, or is there any thing else needed?

**Comment by justvanrossum** [comment]
Wow, fantastic, @khaled! I'd say "yes" to drop AppVeyor, but @anthrotype's opinion is worth more than mine.

(Btw. thank you so much for your recent flood of fixes and improvements!)

**Review by anthrotype — APPROVED** [review]
thank you Khaled!

**Comment by anthrotype** [comment]
> "yes" to drop AppVeyor

+1

**Comment by anthrotype** [comment]
before removing appveyor you need to make sure that the wheel uploading still works
i think the GHA workflow uses the TRAVIS_OS_NAME env var to create a unique (per-platform) zip file name and right now there's an if statement that assumes either macosx or linux.

**Comment by anthrotype** [comment]
```diff
-    - name: Set up environment variables
-      run: |
-        if [ "macos-latest" == "${{ matrix.os }}" ]; then
-         echo "TRAVIS_OS_NAME=osx" >> $GITHUB_ENV
-        else
-          echo "TRAVIS_OS_NAME=ubuntu" >> $GITHUB_ENV
-        fi
      - name: Install dependencies
        run: pip install cibuildwheel
      - name: Build Wheels
        run: python -m cibuildwheel --output-dir wheelhouse
     - uses: actions/upload-artifact@v2
       with:
-        name: uharfbuzz-${{ env.TRAVIS_OS_NAME }}
+        name: uharfbuzz-${{ matrix.os }}
        path: wheelhouse/*.whl
```

**Pull request merged**
