### PR TITLE
Add font extents functions

### LINKED ISSUE #106: Obtaining `hb_font_extents_t`?
Currently the binding to `hb_font_get_extents_for_direction()` does not exist.

I think it's useful to implement `hb-view` ish utilities in Python. What are your thoughts?

### PR DESCRIPTION
**Pull request by takaakifuji**
Callbacks are also implemented. Closes #106.

### CODE REVIEW

**Comment by takaakifuji** [comment]
Thanks. I'll look into the pypy3.8-specific issue.

**Comment by takaakifuji** [comment]
I'm not following the technical details, but adding
```
cython>=0.29.1;  platform_python_implementation != "PyPy"
cython==0.29.25; platform_python_implementation == "PyPy"
```
to `requirements-dev.txt` and `pyproject.toml` may mitigate the CI failure.

`cython==0.29.26` on `pypy3.8-7.3.7` emits
```
src/uharfbuzz/_harfbuzz.cpp:17670:3: error: excess elements in struct initializer
  0, /*tp_pypy_flags*/
  ^
```
on compilation, but `cython==0.29.25` doesn't fail on my local machine.

> **Missing tp_vectorcall slot in PyTypeObject on py3.8**  
> https://foss.heptapod.net/pypy/pypy/-/issues/3618

Or, maybe we could just wait until `cython==0.29.27` gets landed.

Thus, I think the CI failure has nothing to do with this PR.

**Comment by takaakifuji** [comment]
Cython 0.29.27 has landed on 2022-01-28 [with the fix for PyPy](https://cython.readthedocs.io/en/stable/src/changes.html#id1). Re-running the workflow would just fix the failure.

**Review by anthrotype — APPROVED** [review]
LGTM!

**Pull request merged**
