### PR TITLE
update to 2.6.8

### PR DESCRIPTION
**Pull request by justvanrossum**
This supersedes #44.

### CODE REVIEW

**Comment by ebraminio** [comment]
Please consider using meson after the update also, #29, thanks :)

**Comment by justvanrossum** [comment]
> Please consider using meson after the update also, #29, thanks :)

I know, but I don't know enough to make that happen myself, so here's to hoping that one of the other maintainers will have an opportunity to have a look at that...

**Comment by anthrotype** [comment]
> Please consider using meson

Thanks Ebrahim for waiting a bit more before dropping cmake support. We'll probably end up building the sigle src/harfbuzz.cc file directly with setuptools and skip HarfBuzz build system altogether, like @khaledhosny has suggested. I need to find the time to do that soon.

**Comment by ebraminio** [comment]
No problem, [harfbuzzjs](https://github.com/harfbuzz/harfbuzzjs/blob/master/build.sh) is using harfbuzz.cc (even CC src/hb*.cc works) from the beginning that may help you.

**Pull request merged**
