### PR TITLE
Test passing PyCapsule to DrawFuncs callbacks

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by behdad** [comment]
Wow. This is some magic @justvanrossum would love!

**Comment by khaledhosny** [comment]
> Wow. This is some magic @justvanrossum would love!

Already in latest FontGoggles https://github.com/justvanrossum/fontgoggles/pull/269

**Comment by justvanrossum** [comment]
Deploy first, test later :)

**Comment by khaledhosny** [comment]
This is failing on Windows, and with PyPy on Linux. No idea if any of this is expected.

**Comment by khaledhosny** [comment]
> Deploy first, test later :)

FontGoogles **is** the test, this PR is just the paper work 😄

**Comment by khaledhosny** [comment]
The failures are because ctypes can’t find the C callback functions. There are probably some magic incarnation to export the symbols in all configurations, but I have no idea what is it. May be we should skip the test if the symbols can’t be found? Or xfail on the known to fail combinations so that ones that pass now don’t silently fail later?

**Comment by justvanrossum** [comment]
Could it be `__declspec`? https://stackoverflow.com/questions/2284610/what-is-declspec-and-when-do-i-need-to-use-it

**Comment by khaledhosny** [comment]
> Could it be `__declspec`? https://stackoverflow.com/questions/2284610/what-is-declspec-and-when-do-i-need-to-use-it

I tried to use `HB_EXTERN` which supposedly handle this, but I now tried setting it directly.

**Comment by behdad** [comment]
`HB_DLL_EXPORT` is internal to harfbuzz and not checked by the external headers.

**Comment by khaledhosny** [comment]
> `HB_DLL_EXPORT` is internal to harfbuzz and not checked by the external headers.

I see. Setting `__declspec` directly seems to be working.

**Comment by khaledhosny** [comment]
Test now xfails on PyPy, because its ctypes module has no pythonapi attribute and I couldn’t find a replacement.

**Review by justvanrossum — APPROVED** [review]

**Pull request merged**
