### PR TITLE
Update to HarfBuzz 4.0.0

### PR DESCRIPTION
**Pull request by khaledhosny**
In preparation for the stabilization hb-draw API.

TODO:

- [x]  Review the Python API and align it with the new HarfBuzz API
- [x]  Deprecate old Python API if needed

### CODE REVIEW

**Comment by justvanrossum** [comment]
Blackrenderer uses the draw API, and may be a good test case. Let me know if/when you want me to try out this PR.

**Comment by khaledhosny** [comment]
> Blackrenderer uses the draw API, and may be a good test case. Let me know if/when you want me to try out this PR.

It should be ready for testing now.

**Comment by garretrieger** [comment]
Is this able to be merged now? We're planning on PR'ing the addition of the repacker API but it's blocked on updating to 4.0.0.

**Comment by khaledhosny** [comment]
Merged, we can fix any issues before next release.

**Comment by justvanrossum** [comment]
I just ran my blackrenderer tests with this version, and it works perfectly. 

I do see differences between the previous int-only output and the current float coordinates, but that's obviously to be expected. I'll just have to adapt my expected results in those few cases.

**Comment by khaledhosny** [comment]
Excellent !

**Pull request merged**
