### PR TITLE
Add `font.glyph_to_string` to README.md

### PR DESCRIPTION
**Pull request by roberto-arista**

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]

**Comment by anthrotype** [comment]
there seems to be two methods that do the same thing (convert a gid to a glyph name), i.e. hb_font_get_glyph_name and hb_font_glypy_to_string, I wonder why and what's the diff /cc @khaledhosny @behdad

**Comment by khaledhosny** [comment]
> there seems to be two methods that do the same thing (convert a gid to a glyph name), i.e. hb_font_get_glyph_name and hb_font_glyph_to_string, I wonder why and what's the diff /cc @khaledhosny @behdad

`hb_font_glyph_to_string()` always returns a string and will synthesize a name (`gidNNN`) if there is no glyph name, while `hb_font_get_glyph_name()` only returns glyph names if present.

**Comment by anthrotype** [comment]
ok thanks. So I suppose get_glyph_name() here is appropriate in the README and we can merge this?

**Comment by khaledhosny** [comment]
For uses like this, `font.glyph_to_string()` is preferable, as `font.get_glyph_name()` can return None.

**Comment by anthrotype** [comment]
right ok, @roberto-arista can you use glyph_to_string() instead? thanks!

**Comment by roberto-arista** [comment]
done!

**Pull request merged**
