### PR TITLE
Replace Travis CI with Github Actions build & deploy setup

### LINKED ISSUE #70: move to Github Actions CI before travis.org shutdown
we should replace Travis CI with Github Actions, at least for the mac and linux builds, the windows appveyor can stay for now.

[cibuildwheel](https://github.com/joerick/cibuildwheel) docs say that it works with github actions.

I don't have time to work on this, but i'm happy to review PRs

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes #70

### CODE REVIEW

**Comment by anthrotype** [comment]
@justvanrossum I configured github actions to automatically create a new Github Release using the text of the annotated git tag as the release notes (they are also formatted automatically as markdow), similarly to how I did to other repos of mine. Basically, when you want to tag a new release, on your _local_ repository you create an annotated tag (`git tag -a v0.15.0`, or `-s` if you want to also sign the tag), then your default git text editor will open and you can write the changelog in there which will be stored in the git tag message (e.g. `git show v0.15.0`). Then you trigger the CI by pushing the tag to the upstream repository (I usually do `git push --follow-tags`, you can also push just the tag with `git push origin v0.15.0`).

However, if you prefer to not do that automatically and instead use the web interface to draft new releases, I can remove that.

**Comment by anthrotype** [comment]
I think this is ready to go

**Comment by anthrotype** [comment]
as a bonus, with this PR we'll also get wheels for python3.9

**Review by justvanrossum — APPROVED** [review]

**Comment by anthrotype** [comment]
@justvanrossum I added some notes on the README.md on how to make a release, in case I'm not around next time you need to cut one
https://github.com/harfbuzz/uharfbuzz#how-to-make-a-release

I'm gonna try to push a pre-release tag (e.g. ending `a1` for alphas or `b2` for betas or `rc3` for release-candidates) now just to check that the auto-deployment actually works

**Comment by justvanrossum** [comment]
Thanks, that's very helpful!

**Comment by anthrotype** [comment]
ok, our bot managed to create the pre-release: https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.14.1a1

but it failed to upload because I forgot to build the uharfbuzz sdist we also need to install cython. I'll fix that

**Comment by anthrotype** [comment]
upload this time worked => https://pypi.org/project/uharfbuzz/0.14.1a2

you're ready for next stable release

**Comment by anthrotype** [comment]
if you don't see the windows wheels in https://pypi.org/project/uharfbuzz/0.14.1a2/#files yet, it's because appveyor is slower to complete

**Comment by anthrotype** [comment]
I haven't bothered also replacing Appveyor with Github Actions for the windows builds since it still works fine. Next time if things change maybe.

**Comment by justvanrossum** [comment]
Thanks!

> I haven't bothered also replacing Appveyor with Github Actions for the windows builds since it still works fine. Next time if things change maybe.

Would it take much more than adding `windows-latest` to the `os` list?

**Comment by anthrotype** [comment]
Maybe but you never know with these things until you do them

**Pull request merged**
