### PR TITLE
Build coretext shaper by default on OS X

### PR DESCRIPTION
**Pull request by simoncozens**
Obvious PR to FontGoggles also incoming.

### CODE REVIEW

**Comment by anthrotype** [comment]
thanks! It would also be nice to have the CI run some basic tests on mac only (but mind that #70)

**Comment by anthrotype** [comment]
looks like it failed to build, see https://travis-ci.org/github/harfbuzz/uharfbuzz/jobs/759341255

**Comment by anthrotype** [comment]
Hm, it did work when I built this locally (using clang on macOS 10.15.7), I think the Travis worker uses macOS 10.13.
I don't quite understand the compile error we get on Travis:

```
gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -DHB_NO_MT=1 -DHB_EXPERIMENTAL_API=1 -DHAVE_CORETEXT=1 -Iharfbuzz/src -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c harfbuzz/src/harfbuzz.cc -o build/temp.macosx-10.6-intel-3.6/harfbuzz/src/harfbuzz.o -std=c++11
  In file included from harfbuzz/src/harfbuzz.cc:55:
  In file included from harfbuzz/src/hb-coretext.cc:35:
  In file included from harfbuzz/src/hb-coretext.h:37:
  In file included from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:
  In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:147:
  /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/TextUtils.h:288:3: error: reference to 'OffsetTable' is ambiguous
    OffsetTable     offsets,
    ^
  /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/IntlResources.h:115:41: note: candidate found by name lookup is 'OffsetTable'
  typedef OffPair                         OffsetTable[3];
                                          ^
  harfbuzz/src/hb-open-file.hh:81:16: note: candidate found by name lookup is 'OT::OffsetTable'
  typedef struct OffsetTable
                 ^
  In file included from harfbuzz/src/harfbuzz.cc:55:
```

I'll try to fix #70 first so we have a stable Github CI setup and maybe you can then rebase on master and it'll automagically work?

**Comment by behdad** [comment]
You might as well enable Uniscribe on WIndows (and wire it to FontGoggles) as well.

As for the build issue, looks like the single-file harfbuzz.cc doesn't work with CoreText because of a name clash. Let me try to fix that in HarfBuzz upstream.

**Comment by simoncozens** [comment]
FontGoggles is very much non-portable at the moment, so a Windows build is not worthwhile. I've been looking at porting the UI to PyQt to make it cross-platform, but it would be a lot of work.

**Comment by behdad** [comment]
> As for the build issue, looks like the single-file harfbuzz.cc doesn't work with CoreText because of a name clash. Let me try to fix that in HarfBuzz upstream.

This is fixed upstream now: https://github.com/harfbuzz/harfbuzz/commit/505b3fc6cfbed95a4101c9a9c75a76645eb6fb6b

**Comment by anthrotype** [comment]
Thanks Behdad!

**Comment by anthrotype** [comment]
@simoncozens maybe you can try rebasing on master branch to take in the Github Actions setup changes from #73

**Comment by justvanrossum** [comment]
Now that there's a hb release containing the fix (I upgraded our hb submodule to 2.8.0), a rebase would be grand.

**Comment by simoncozens** [comment]
There’s no conflict. It still fits.

**Comment by justvanrossum** [comment]
Thanks Khaled!

**Comment by simoncozens** [comment]
Thanks Khaled. But I'm genuinely interested, just in terms of improving how I use git/github in the future - why did that need a rebase when there were no conflicts? If it had just been merged without rebase, wouldn't it have just been applied on top of master? Or was it something to do with allowing it to be squashed without a merge commit?

**Comment by anthrotype** [comment]
to make it run with the updated Github Actions setup

**Comment by simoncozens** [comment]
Ah! That make sense. Thanks!

**Pull request merged**
